// Code generated by "stringer -type DataType -linecomment"; DO NOT EDIT.

package cdn

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DataTypeBandwidth-1]
	_ = x[DataType302Bandwidth-2]
	_ = x[DataType302mBandwidth-3]
	_ = x[DataTypeFlow-4]
	_ = x[DataType302Flow-5]
	_ = x[DataType302mFlow-6]
}

const _DataType_name = "bandwidth302bandwidth302mbandwidthflow302flow302mflow"

var _DataType_index = [...]uint8{0, 9, 21, 34, 38, 45, 53}

func (i DataType) String() string {
	i -= 1
	if i < 0 || i >= DataType(len(_DataType_index)-1) {
		return "DataType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DataType_name[_DataType_index[i]:_DataType_index[i+1]]
}
