// THIS FILE IS GENERATED BY api-generator, DO NOT EDIT DIRECTLY!

package apis

import (
	"context"
	"encoding/base64"
	"encoding/json"
	auth "github.com/qiniu/go-sdk/v7/auth"
	modifyobjectlifecycle "github.com/qiniu/go-sdk/v7/storagev2/apis/modify_object_life_cycle"
	errors "github.com/qiniu/go-sdk/v7/storagev2/errors"
	httpclient "github.com/qiniu/go-sdk/v7/storagev2/http_client"
	region "github.com/qiniu/go-sdk/v7/storagev2/region"
	"strconv"
	"strings"
)

type innerModifyObjectLifeCycleRequest modifyobjectlifecycle.Request

func (pp *innerModifyObjectLifeCycleRequest) getBucketName(ctx context.Context) (string, error) {
	return strings.SplitN(pp.Entry, ":", 2)[0], nil
}
func (path *innerModifyObjectLifeCycleRequest) buildPath() ([]string, error) {
	var allSegments []string
	if path.Entry != "" {
		allSegments = append(allSegments, base64.URLEncoding.EncodeToString([]byte(path.Entry)))
	} else {
		return nil, errors.MissingRequiredFieldError{Name: "Entry"}
	}
	if path.ToIaAfterDays != 0 {
		allSegments = append(allSegments, "toIAAfterDays", strconv.FormatInt(path.ToIaAfterDays, 10))
	}
	if path.ToArchiveAfterDays != 0 {
		allSegments = append(allSegments, "toArchiveAfterDays", strconv.FormatInt(path.ToArchiveAfterDays, 10))
	}
	if path.ToDeepArchiveAfterDays != 0 {
		allSegments = append(allSegments, "toDeepArchiveAfterDays", strconv.FormatInt(path.ToDeepArchiveAfterDays, 10))
	}
	if path.ToArchiveIrAfterDays != 0 {
		allSegments = append(allSegments, "toArchiveIRAfterDays", strconv.FormatInt(path.ToArchiveIrAfterDays, 10))
	}
	if path.DeleteAfterDays != 0 {
		allSegments = append(allSegments, "deleteAfterDays", strconv.FormatInt(path.DeleteAfterDays, 10))
	}
	return allSegments, nil
}
func (j *innerModifyObjectLifeCycleRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal((*modifyobjectlifecycle.Request)(j))
}
func (j *innerModifyObjectLifeCycleRequest) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, (*modifyobjectlifecycle.Request)(j))
}
func (request *innerModifyObjectLifeCycleRequest) getAccessKey(ctx context.Context) (string, error) {
	if request.Credentials != nil {
		if credentials, err := request.Credentials.Get(ctx); err != nil {
			return "", err
		} else {
			return credentials.AccessKey, nil
		}
	}
	return "", nil
}

type ModifyObjectLifeCycleRequest = modifyobjectlifecycle.Request
type ModifyObjectLifeCycleResponse = modifyobjectlifecycle.Response

// 修改已上传对象的生命周期
func (storage *Storage) ModifyObjectLifeCycle(ctx context.Context, request *ModifyObjectLifeCycleRequest, options *Options) (response *ModifyObjectLifeCycleResponse, err error) {
	if options == nil {
		options = &Options{}
	}
	innerRequest := (*innerModifyObjectLifeCycleRequest)(request)
	serviceNames := []region.ServiceName{region.ServiceRs}
	var pathSegments []string
	pathSegments = append(pathSegments, "lifecycle")
	if segments, err := innerRequest.buildPath(); err != nil {
		return nil, err
	} else {
		pathSegments = append(pathSegments, segments...)
	}
	path := "/" + strings.Join(pathSegments, "/")
	var rawQuery string
	req := httpclient.Request{Method: "POST", ServiceNames: serviceNames, Path: path, RawQuery: rawQuery, AuthType: auth.TokenQiniu, Credentials: innerRequest.Credentials}
	var queryer region.BucketRegionsQueryer
	if storage.client.GetRegions() == nil && storage.client.GetEndpoints() == nil {
		queryer = storage.client.GetBucketQueryer()
		if queryer == nil {
			bucketHosts := httpclient.DefaultBucketHosts()
			var err error
			if options.OverwrittenBucketHosts != nil {
				if bucketHosts, err = options.OverwrittenBucketHosts.GetEndpoints(ctx); err != nil {
					return nil, err
				}
			}
			queryerOptions := region.BucketRegionsQueryerOptions{UseInsecureProtocol: storage.client.UseInsecureProtocol(), HostFreezeDuration: storage.client.GetHostFreezeDuration(), Client: storage.client.GetClient()}
			if hostRetryConfig := storage.client.GetHostRetryConfig(); hostRetryConfig != nil {
				queryerOptions.RetryMax = hostRetryConfig.RetryMax
			}
			if queryer, err = region.NewBucketRegionsQueryer(bucketHosts, &queryerOptions); err != nil {
				return nil, err
			}
		}
	}
	if queryer != nil {
		bucketName := options.OverwrittenBucketName
		var accessKey string
		var err error
		if bucketName == "" {
			if bucketName, err = innerRequest.getBucketName(ctx); err != nil {
				return nil, err
			}
		}
		if accessKey, err = innerRequest.getAccessKey(ctx); err != nil {
			return nil, err
		} else if accessKey == "" {
			if credentialsProvider := storage.client.GetCredentials(); credentialsProvider != nil {
				if creds, err := credentialsProvider.Get(ctx); err != nil {
					return nil, err
				} else if creds != nil {
					accessKey = creds.AccessKey
				}
			}
		}
		if accessKey != "" && bucketName != "" {
			req.Region = queryer.Query(accessKey, bucketName)
		}
	}
	resp, err := storage.client.Do(ctx, &req)
	if err != nil {
		return nil, err
	}
	return &ModifyObjectLifeCycleResponse{}, resp.Body.Close()
}
