// THIS FILE IS GENERATED BY api-generator, DO NOT EDIT DIRECTLY!

package apis

import (
	"context"
	auth "github.com/qiniu/go-sdk/v7/auth"
	uplog "github.com/qiniu/go-sdk/v7/internal/uplog"
	addbucketrules "github.com/qiniu/go-sdk/v7/storagev2/apis/add_bucket_rules"
	errors "github.com/qiniu/go-sdk/v7/storagev2/errors"
	httpclient "github.com/qiniu/go-sdk/v7/storagev2/http_client"
	region "github.com/qiniu/go-sdk/v7/storagev2/region"
	uptoken "github.com/qiniu/go-sdk/v7/storagev2/uptoken"
	"net/url"
	"strconv"
	"strings"
	"time"
)

type innerAddBucketRulesRequest addbucketrules.Request

func (form *innerAddBucketRulesRequest) getBucketName(ctx context.Context) (string, error) {
	return form.Bucket, nil
}
func (form *innerAddBucketRulesRequest) build() (url.Values, error) {
	formValues := make(url.Values)
	if form.Bucket != "" {
		formValues.Set("bucket", form.Bucket)
	} else {
		return nil, errors.MissingRequiredFieldError{Name: "Bucket"}
	}
	if form.Name != "" {
		formValues.Set("name", form.Name)
	} else {
		return nil, errors.MissingRequiredFieldError{Name: "Name"}
	}
	formValues.Set("prefix", form.Prefix)
	formValues.Set("delete_after_days", strconv.FormatInt(form.DeleteAfterDays, 10))
	formValues.Set("to_line_after_days", strconv.FormatInt(form.ToIaAfterDays, 10))
	formValues.Set("to_archive_after_days", strconv.FormatInt(form.ToArchiveAfterDays, 10))
	formValues.Set("to_deep_archive_after_days", strconv.FormatInt(form.ToDeepArchiveAfterDays, 10))
	formValues.Set("to_archive_ir_after_days", strconv.FormatInt(form.ToArchiveIrAfterDays, 10))
	return formValues, nil
}

type AddBucketRulesRequest = addbucketrules.Request
type AddBucketRulesResponse = addbucketrules.Response

// 增加空间规则
func (storage *Storage) AddBucketRules(ctx context.Context, request *AddBucketRulesRequest, options *Options) (*AddBucketRulesResponse, error) {
	if options == nil {
		options = &Options{}
	}
	innerRequest := (*innerAddBucketRulesRequest)(request)
	serviceNames := []region.ServiceName{region.ServiceBucket}
	if innerRequest.Credentials == nil && storage.client.GetCredentials() == nil {
		return nil, errors.MissingRequiredFieldError{Name: "Credentials"}
	}
	pathSegments := make([]string, 0, 2)
	pathSegments = append(pathSegments, "rules", "add")
	path := "/" + strings.Join(pathSegments, "/")
	var rawQuery string
	body, err := innerRequest.build()
	if err != nil {
		return nil, err
	}
	bucketName := options.OverwrittenBucketName
	if bucketName == "" {
		var err error
		if bucketName, err = innerRequest.getBucketName(ctx); err != nil {
			return nil, err
		}
	}
	uplogInterceptor, err := uplog.NewRequestUplog("addBucketRules", bucketName, "", func() (string, error) {
		credentials := innerRequest.Credentials
		if credentials == nil {
			credentials = storage.client.GetCredentials()
		}
		putPolicy, err := uptoken.NewPutPolicy(bucketName, time.Now().Add(time.Hour))
		if err != nil {
			return "", err
		}
		return uptoken.NewSigner(putPolicy, credentials).GetUpToken(ctx)
	})
	if err != nil {
		return nil, err
	}
	req := httpclient.Request{Method: "POST", ServiceNames: serviceNames, Path: path, RawQuery: rawQuery, Endpoints: options.OverwrittenEndpoints, Region: options.OverwrittenRegion, Interceptors: []httpclient.Interceptor{uplogInterceptor}, AuthType: auth.TokenQiniu, Credentials: innerRequest.Credentials, RequestBody: httpclient.GetFormRequestBody(body), OnRequestProgress: options.OnRequestProgress}
	if options.OverwrittenEndpoints == nil && options.OverwrittenRegion == nil && storage.client.GetRegions() == nil {
		bucketHosts := httpclient.DefaultBucketHosts()
		if options.OverwrittenBucketHosts != nil {
			req.Endpoints = options.OverwrittenBucketHosts
		} else {
			req.Endpoints = bucketHosts
		}
	}
	resp, err := storage.client.Do(ctx, &req)
	if err != nil {
		return nil, err
	}
	return &AddBucketRulesResponse{}, resp.Body.Close()
}
