// THIS FILE IS GENERATED BY api-generator, DO NOT EDIT DIRECTLY!

// 使用 Multipart Upload 方式上传数据前，必须先调用 API 来获取一个全局唯一的 UploadId，后续的块数据通过 uploadPart API 上传，整个文件完成 completeMultipartUpload API，已经上传块的删除 abortMultipartUpload API 都依赖该 UploadId
package resumable_upload_v2_initiate_multipart_upload

import (
	"context"
	"encoding/base64"
	"encoding/json"
	httpclient "github.com/qiniu/go-sdk/v7/storagev2/http_client"
	region "github.com/qiniu/go-sdk/v7/storagev2/region"
	uptoken "github.com/qiniu/go-sdk/v7/storagev2/uptoken"
	"strings"
)

type RequestPath struct {
	fieldBucketName string
	fieldObjectName string
}

func (pp *RequestPath) GetBucketName() string {
	return pp.fieldBucketName
}
func (pp *RequestPath) SetBucketName(value string) *RequestPath {
	pp.fieldBucketName = value
	return pp
}
func (pp *RequestPath) GetObjectName() string {
	return pp.fieldObjectName
}
func (pp *RequestPath) SetObjectName(value string) *RequestPath {
	pp.fieldObjectName = value
	return pp
}
func (path *RequestPath) build() []string {
	var allSegments []string
	if path.fieldBucketName != "" {
		allSegments = append(allSegments, path.fieldBucketName)
	}
	if path.fieldObjectName != "" {
		allSegments = append(allSegments, "objects", base64.URLEncoding.EncodeToString([]byte(path.fieldObjectName)))
	} else {
		allSegments = append(allSegments, "objects", "~")
	}
	return allSegments
}

type innerNewMultipartUpload struct {
	UploadId  string `json:"uploadId,omitempty"` // 初始化文件生成的 id
	ExpiredAt int64  `json:"expireAt,omitempty"` // UploadId 的过期时间 UNIX 时间戳，过期之后 UploadId 不可用
}

// 返回本次 MultipartUpload 相关信息
type NewMultipartUpload struct {
	inner innerNewMultipartUpload
}

func (j *NewMultipartUpload) GetUploadId() string {
	return j.inner.UploadId
}
func (j *NewMultipartUpload) SetUploadId(value string) *NewMultipartUpload {
	j.inner.UploadId = value
	return j
}
func (j *NewMultipartUpload) GetExpiredAt() int64 {
	return j.inner.ExpiredAt
}
func (j *NewMultipartUpload) SetExpiredAt(value int64) *NewMultipartUpload {
	j.inner.ExpiredAt = value
	return j
}
func (j *NewMultipartUpload) MarshalJSON() ([]byte, error) {
	return json.Marshal(&j.inner)
}
func (j *NewMultipartUpload) UnmarshalJSON(data []byte) error {
	return json.Unmarshal(data, &j.inner)
}

// 获取 API 所用的响应体参数
type ResponseBody = NewMultipartUpload

// 调用 API 所用的请求
type Request struct {
	BucketHosts region.EndpointsProvider
	Path        RequestPath
	UpToken     uptoken.Provider
}

func (request Request) getBucketName(ctx context.Context) (string, error) {
	if request.UpToken != nil {
		if putPolicy, err := request.UpToken.RetrievePutPolicy(ctx); err != nil {
			return "", err
		} else {
			return putPolicy.GetBucketName()
		}
	}
	return "", nil
}
func (request Request) getAccessKey(ctx context.Context) (string, error) {
	if request.UpToken != nil {
		return request.UpToken.RetrieveAccessKey(ctx)
	}
	return "", nil
}

// 获取 API 所用的响应
type Response struct {
	Body ResponseBody
}

// API 调用客户端
type Client struct {
	client *httpclient.HttpClient
}

// 创建 API 调用客户端
func NewClient(options *httpclient.HttpClientOptions) *Client {
	client := httpclient.NewHttpClient(options)
	return &Client{client: client}
}
func (client *Client) Send(ctx context.Context, request *Request) (*Response, error) {
	serviceNames := []region.ServiceName{region.ServiceUp}
	var pathSegments []string
	pathSegments = append(pathSegments, "buckets")
	pathSegments = append(pathSegments, request.Path.build()...)
	pathSegments = append(pathSegments, "uploads")
	path := "/" + strings.Join(pathSegments, "/")
	req := httpclient.Request{Method: "POST", ServiceNames: serviceNames, Path: path, UpToken: request.UpToken}
	var queryer *region.BucketRegionsQueryer
	if client.client.GetRegions() == nil && client.client.GetEndpoints() == nil {
		queryer = client.client.GetBucketQueryer()
		if queryer == nil {
			bucketHosts := httpclient.DefaultBucketHosts()
			var err error
			if request.BucketHosts != nil {
				if bucketHosts, err = request.BucketHosts.GetEndpoints(ctx); err != nil {
					return nil, err
				}
			}
			if queryer, err = region.NewBucketRegionsQueryer(bucketHosts, nil); err != nil {
				return nil, err
			}
		}
	}
	if queryer != nil {
		bucketName, err := request.getBucketName(ctx)
		if err != nil {
			return nil, err
		}
		accessKey, err := request.getAccessKey(ctx)
		if err != nil {
			return nil, err
		}
		req.Region = queryer.Query(accessKey, bucketName)
	}
	var respBody ResponseBody
	if _, err := client.client.AcceptJson(ctx, &req, &respBody); err != nil {
		return nil, err
	}
	return &Response{Body: respBody}, nil
}
