// THIS FILE IS GENERATED BY api-generator, DO NOT EDIT DIRECTLY!

// 设置存储空间的镜像源
package set_buckets_mirror

import credentials "github.com/qiniu/go-sdk/v7/storagev2/credentials"

// 调用 API 所用的请求
type Request struct {
	Bucket      string                          // 需要设定镜像源的目标空间名
	SrcSiteUrl  string                          // 镜像源的访问域名，必须设置为形如 `http(s)://source.com` 或 `http(s)://114.114.114.114` 的字符串
	Host        string                          // 回源时使用的 `Host` 头部值
	Credentials credentials.CredentialsProvider // 鉴权参数，用于生成鉴权凭证，如果为空，则使用 HTTPClientOptions 中的 CredentialsProvider
}

// 获取 API 所用的响应
type Response struct{}
