// THIS FILE IS GENERATED BY api-generator, DO NOT EDIT DIRECTLY!

package apis

import (
	httpclient "github.com/qiniu/go-sdk/v7/storagev2/http_client"
	region "github.com/qiniu/go-sdk/v7/storagev2/region"
)

// API 客户端
type Media struct {
	client *httpclient.Client
}

// 创建 API 客户端
func NewMedia(options *httpclient.Options) *Media {
	return &Media{client: httpclient.NewClient(options)}
}

// API 客户端选项
type Options struct {
	OverwrittenBucketHosts region.EndpointsProvider
	OverwrittenBucketName  string
	OverwrittenEndpoints   region.EndpointsProvider
	OverwrittenRegion      region.RegionsProvider
	OnRequestProgress      func(uint64, uint64)
}
